import{S as p,i as c}from"./assets/vendor-5b791d57.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();function m(o){const e="42305362-292fb567d2617ee346426e642",s="https://pixabay.com",a="/api/",t=`?key=${e}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`,r=s+a+t;return fetch(r).then(i=>i.json())}let l;const n={form:document.querySelector(".form"),input:document.querySelector(".input-search"),button:document.querySelector(".button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};function f(o){return o.map(e=>`
      <li class="gal-item"><a href="${e.largeImageURL}">
            <img class="gal-image" src="${e.webformatURL}" alt="${e.tags}"></a>
            <div class="par-sect">
            <p> <span class="par-informatiom">Likes</span> <br/> ${e.likes}</p>
            <p><span class="par-informatiom">Views</span> <br/> ${e.views}</p>
            <p><span class="par-informatiom">Comments</span> <br/> ${e.comments}</p>
            <p><span class="par-informatiom">Downloads</span> <br/> ${e.downloads}</p>
            </div>
            </li>
      `).join("")}function y(o){const e=f(o);n.gallery.innerHTML=e,typeof l<"u"?l.refresh():l=new p(".gallery a",{captionsData:"alt",captionDelay:250})}n.loader.style.display="none";n.form.addEventListener("submit",d);function d(o){if(o.preventDefault(),n.input.value.trim()===""||n.input.value.trim().length===0)return;u(),n.loader.style.display="block";const e=o.target.elements.search.value;m(e).then(s=>{s.hits.length===0?(u(),c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"})):y(s.hits)}).catch(s=>{c.error({message:`Error: ${s.message}`})}).finally(()=>{n.loader.style.display="none"}),o.target.reset()}function u(){n.gallery.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
